let namaDepan = "Narendra";
let namaTengah = "Dwi al";
let namaBelakang = "Mustafa";
let alamat = "Jl Sedayu Indah RT3 RW2";
let usia = "15";
let ttl = "Semarang 19 Maret 2009";
let gender = "Male";
let Agama = "Islam";
let email = "narendradwialmusthofa@gmail.com";
let berat = "62";
let Tinggi = "167";
let hobi = "main game";
let cita = "Pengusaha";
let pekerjaan = "Pelajar";
let sekolah = "SMKN 1 SAYUNG";
let jurusan = "PPLG";
document.write(" nama saya adalah " + namaDepan + " " + namaTengah + " " + namaBelakang + " Saya tinggal di " + alamat + " Pada tahun 2025 ini usia saya adalah " + usia + " Saya lahir di " + ttl + " gender saya adalah " + gender + " saya beragama " + Agama + " alamat email saya adalah " + email + " saya memiliki berat badan " + berat + " kg dengan tinggi " + Tinggi + " cm. Saya sangat senang " + hobi + " karena saya memiliki cita-cita " + cita + " saat ini saya adalah seorang " + pekerjaan + " yang bersekolah di " + sekolah + " pada jurusan " + jurusan);